#!/bin/bash
OM_ENV_NAME=xlab
OM_DOMAIN_NAME=gcp.harnessingunicorns.io

function askUser() {
        read -p "$1: " __val
        # first, strip underscores
        CLEAN=${__val//_/}
        # next, replace spaces with underscores
        CLEAN=${CLEAN// /_}
        # now, clean out anything that's not alphanumeric or an underscore or a hyphen
        CLEAN=${CLEAN//[^a-zA-Z0-9_-]/}
        echo "${CLEAN}"

        return 0
}
function askYes() {
        ANSWER="$(askUser "$1 (Y|y) ")"
        if [ "$ANSWER" == "${ANSWER#[Yy]}" ]; then
                return 1
        else
                return 0
        fi
}



nslookup pcf.$OM_ENV_NAME.$OM_DOMAIN_NAME > /dev/null 2>&1; RETVAL=$?

while [[ ! $RETVAL -eq 0 ]]; do
	askYes "pcf.$OM_ENV_NAME.$OM_DOMAIN_NAME not found.  Try again?"; RESP=$?
	if [[ ! $RESP -eq 0 ]]; then
		echo "Ok.  Exiting."
		exit 1
	fi
	nslookup pcf.$OM_ENV_NAME.$OM_DOMAIN_NAME > /dev/null 2>&1; RETVAL=$?
done

nslookup pcf.$OM_ENV_NAME.$OM_DOMAIN_NAME
